version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5446:5432"
    env_file:
      - ./.env
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  postgres_to_es:
    build: ./postgres_to_es
    env_file:
      - ./.env
    depends_on:
      - db
      - elasticsearch
    restart: always

volumes:
  esdata: